"""add chat_enabled

Revision ID: 7b9157c424e3
Revises: dc4f64377f1e
Create Date: 2026-03-24 12:00:09.904527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b9157c424e3'
down_revision: Union[str, Sequence[str], None] = 'dc4f64377f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackMate_matches', sa.Column('invite_sender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackMate_matches', 'invite_sender')
    # ### end Alembic commands ###
